# Generated by Django 4.1.4 on 2022-12-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
