# Generated by Django 4.1.5 on 2023-01-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='descripion',
            new_name='description',
        ),
    ]
