# Generated by Django 4.1.4 on 2022-12-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Softuni', 'Softuni'), ('Google', 'Google'), ('FACEBOOK', 'FACEBOOK')], max_length=8),
        ),
    ]
