# Generated by Django 4.1.4 on 2022-12-26 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employee_options_remove_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='deparment_id',
            new_name='deparment',
        ),
    ]
